# Generated by Django 4.2.13 on 2024-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('attr_value', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'attr_value'],
                'unique_together': {('category', 'attr_value')},
            },
        ),
        migrations.CreateModel(
            name='RecipeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='collection.attribute')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='collection.recipe')),
            ],
            options={
                'verbose_name': 'Recipe attribute',
            },
        ),
    ]
