# Generated by Django 4.2.13 on 2024-06-19 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_attribute_recipeattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeattribute',
            options={'ordering': ['attribute', 'recipe'], 'verbose_name': 'Recipe attribute'},
        ),
        migrations.AlterUniqueTogether(
            name='recipeattribute',
            unique_together={('recipe', 'attribute')},
        ),
    ]
