# Generated by Django 4.2.13 on 2024-06-03 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_ingredient_options_alter_ingredient_ingr_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['ingr_name', 'preparation']},
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unit', models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('pc', 'pieces'), ('tsp', 'teaspoons'), ('Tbsp', 'tablespoons'), ('cups', 'cups'), ('cloves', 'cloves')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='collection.ingredient')),
            ],
        ),
    ]
