# Generated by Django 4.2.13 on 2024-06-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_ingredient_options_ingredientquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='collection.ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='collection.recipe'),
        ),
    ]
