# Generated by Django 4.2.13 on 2024-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_ingredientquantity_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
