# Generated by Django 4.2.13 on 2024-06-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_ingredientquantity_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'verbose_name': 'Ingredient quantity', 'verbose_name_plural': 'Ingredient quantities'},
        ),
    ]
